// server.js
// Production entry point for Next.js standalone server in Cloud Run.

const path = require('path');

// Ensure standard port and network bindings are set
process.env.PORT = process.env.PORT || '3000';
process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0';
process.env.NODE_ENV = 'production';

console.log(`Starting Next.js production server on port ${process.env.PORT}...`);

try {
  // Use the standalone entrypoint generated by Next.js during build
  require('./.next/standalone/server.js');
} catch (error) {
  console.error('Failed to start Next.js standalone server:', error);
  process.exit(1);
}
